[package]
name = "modkei-tui"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crossbeam-channel.workspace = true
crossterm.workspace = true
modkei-core.workspace = true
modkei-report.workspace = true
ratatui.workspace = true
