[package]
name = "modkei-report"
version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Interactive web report generation and embedded UI for modkei."
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**/*", "static-report/**/*", "Cargo.toml"]

[dependencies]
anyhow.workspace = true
modkei-core.workspace = true
open.workspace = true
serde_json.workspace = true
ctrlc.workspace = true
tiny_http.workspace = true
rust-embed.workspace = true
mime_guess.workspace = true
